version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gooners
    depends_on:
      - mongo
    volumes:
      - ./backend/app:/app
      - ./test_scripts:/test_scripts
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./electron-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./electron-frontend/src:/app/src
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge 